services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - chaticus-data:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  backend:
    build:
      context: ./Backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"  # Optional for debugging, not required by Nginx
    environment:
      DB_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}  # Define in your .env
    networks:
      - backend

  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  chaticus-data: